language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r tests/requirements/all.txt

script:
  - python -m coverage run && coverage report

after_success:
  - bash <(curl -s https://codecov.io/bash)
